nelmio_cors:
    defaults:
        allow_origin: ["http://localhost:4200"] 
        allow_methods: ["GET", "OPTIONS", "POST", "PUT", "DELETE"]
        allow_headers: ["Content-Type", "Authorization"]
        expose_headers: []
        max_age: 3600
    paths:
        "^/nurse": 
            allow_origin: ["http://localhost:4200"]
            allow_methods: ["GET", "OPTIONS", "POST", "PUT", "DELETE"]
            allow_headers: ["Content-Type", "Authorization"]
            max_age: 3600
